### ISSUE TITLE
Cannot initialize the project

### ISSUE THREAD

**Issue by dimensi** [irsyadadl/justd#280]
I created a new nextjs project from scratch, created it with tailwild and all the contents in the src folder.
I ran the command `npx justd-cli@latest init`. Initialization completed successfully, I saw a message about “success”
```sh
## there is my log in vite project, for nextjs i miss it
✔ Initializing.
? Components folder: src/components
? Utils folder: src/utils
? Where would you like to place the CSS file? src/index.css
? No paths key found in tsconfig.json. Please enter the root directory path for the '@/': ./src
✔ Paths added to tsconfig.json.
✔ Installing dependencies.
✔ Configuring.
✔ UI folder created at `"src/components/ui"`
✔ Primitive file saved to `"src/components/ui/primitive.tsx"`
✔ Classes file saved to `"src/utils/classes.ts"`
✔ Theme Provider file saved to `"src/components/theme-provider.tsx"`
✔ Providers file saved to `"src/components/providers.tsx"`
✔ Configuration saved to `justd.json`
✔ Installation complete.


Not sure what to do next?
Visit our documentation at: `https://getjustd.com`

Now try to add some components to your project
by running: `npx justd-cli@latest add`
`      _           _      _ 
     | |_   _ ___| |_ __| |
  _  | | | | / __| __/ _` |
 | |_| | |_| \__ \ || (_| |
  \___/ \__,_|___/\__\__,_|
                           `
```
But src/app/global.css file is not updated, tailwild config is not updated.

Tried to copy and paste content from this doc https://getjustd.com/docs/2.x/getting-started/installation#style-and-primitive. First of all, this is the first time I see such syntax 
```css
@import "tailwindcss";
@plugin 'tailwindcss-animate';
```

In the second still does not run, if I do not add css, I get this error:
```sh
Error evaluating Node.js code
CssSyntaxError: /Users/n.nafranets/projects/cmdk/src/app/globals.css:57:1: `@layer base` is used but no matching `@tailwind base` directive is present.
    [at Input.error (turbopack://[project]/node_modules/postcss/lib/input.js:106:16)]
    [at AtRule.error (turbopack://[project]/node_modules/postcss/lib/node.js:145:32)]
    [at normalizeTailwindDirectives (/Users/n.nafranets/projects/cmdk/node_modules/tailwindcss/lib/lib/normalizeTailwindDirectives.js:72:32)]
    [at /Users/n.nafranets/projects/cmdk/node_modules/tailwindcss/lib/processTailwindFeatures.js:29:98]
    [at plugins (/Users/n.nafranets/projects/cmdk/node_modules/tailwindcss/lib/plugin.js:38:69)]
    [at LazyResult.runOnRoot (turbopack://[project]/node_modules/postcss/lib/lazy-result.js:329:16)]
    [at LazyResult.runAsync (turbopack://[project]/node_modules/postcss/lib/lazy-result.js:258:26)]
    [at LazyResult.async (turbopack://[project]/node_modules/postcss/lib/lazy-result.js:160:30)]
    [at LazyResult.then (turbopack://[project]/node_modules/postcss/lib/lazy-result.js:404:17)]
    [at process.processTicksAndRejections (node:internal/process/task_queues:95:5)]


 ○ Compiling /_error ...
 ```

If I add the css from the documentation, I get one of these:

```sh
warn - The utility `[--button-bg:theme(colors.danger.DEFAULT)]` contains an invalid theme value and was not generated.
```

**Comment by irsyadadl** [comment]
If you are using Tailwinf v3. Your documentation is right here: https://getjustd.com/docs/1.x/getting-started/introduction

The docs you read is when you have setup tailwinf version 4

**Comment by dimensi** [comment]
Well, the documentation doesn't say which version to install, and cli doesn't give any messages about it

<img width="751" alt="Arc 2024-12-18 21 55 36" src="https://github.com/user-attachments/assets/1aa88c79-0af8-41ce-ae12-cfdbb4342412" />

Thanks
